spring.application.name=inventory-management

# Veritaban? Ba?lant?s?
spring.datasource.url=jdbc:mysql://localhost:3306/javaproje_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate Ayarlar? (Tablolar? otomatik günceller)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true